### ISSUE TITLE
Changes to gateway

### ISSUE THREAD

**Issue by AlanSimmons** [x-atlas-consortia/hs-ontology-api#104]
Related to [this PR](https://github.com/x-atlas-consortia/hs-ontology-api/pull/103).

# Deprecated endpoint
/datasets

# New endpoints
/assayclasses
/assayclasses/{name}

These changes should remain in the dev gateway until the changes to both the UBKG API (assayclass model) and the hs-ontology-api endpoints are approved.

**Comment by yuanzhou** [comment]
7/19/2024

Noticed some resource and method definitions with missing integration details for hs-ontology-api API Gateway. Will need to fix them before we can add the new endpoints.

<img width="1137" alt="Screenshot 2024-07-19 at 4 49 24 PM" src="https://github.com/user-attachments/assets/00769d91-922a-4ac3-a92b-f56aa32ff319">
<img width="695" alt="Screenshot 2024-07-19 at 4 37 44 PM" src="https://github.com/user-attachments/assets/141564dc-99ee-40fa-abbb-eedf7b61fa4b">
<img width="1110" alt="Screenshot 2024-07-19 at 4 40 35 PM" src="https://github.com/user-attachments/assets/2e6caf89-6d7e-4ac0-b4b5-a0635bba968c">
<img width="1210" alt="Screenshot 2024-07-19 at 4 41 30 PM" src="https://github.com/user-attachments/assets/a14642b3-a82a-4d8e-9b71-ab2f94292657">
<img width="823" alt="Screenshot 2024-07-19 at 4 42 41 PM" src="https://github.com/user-attachments/assets/a2f65fd0-6d7e-4291-8720-bc8ea764bc1b">
<img width="818" alt="Screenshot 2024-07-19 at 4 19 25 PM" src="https://github.com/user-attachments/assets/0fec94f2-9283-4617-8967-dd74474d9aa9">

**Comment by yuanzhou** [comment]
7/22/2024, @kburke re-imported the yaml to hs-ontology-api API Gateway definitions and we went through all the endpoints. Also deleted the ones that are no longer defined in both ubkg-api and hs-ontology-api Smart API yamls.

**Comment by yuanzhou** [comment]
I've added the new endpoints `/assayclasses` and  `/assayclasses/{name}` in API Gateway. Will deprecate the `/datasets` later after finishing all the tests.
