### ISSUE TITLE
ensure case-insensitivity for application_context

### ISSUE THREAD

**Issue by AlanSimmons** [x-atlas-consortia/hs-ontology-api#111]
#Statement of Problem
Some endpoints that require the *application_context* parameter are not case-insensitive.

**Comment by yuanzhou** [comment]
@AlanSimmons this actually brings up two changes:
- `utils/http_error_string.py` is duplicated in both ubkg-api and hs-ontology-api. We should just use the one from ubkg-api.
- Allow case-insensitive values in https://github.com/x-atlas-consortia/ubkg-api/blob/410a08628ab8ae9b9753b221122fd7279f496bba/src/ubkg_api/utils/http_error_string.py#L159

**Comment by AlanSimmons** [comment]
Current endpoints that use application_context parameter:
- assayclasses
- assayclasses/{class}
- dataset-types
- dataset-types/{name}
- organs
- organs/by-code

**Comment by AlanSimmons** [comment]
Deprecated `hs-ontology-api/utils/http_error_string.py`. 
The controllers for the endpoints that use the application_context parameter had already been refactored. However, the field_* endpoints still pointed to hs-ontology-api's copy, so these were refactored.
