### ISSUE TITLE
ontology soft assay type endpoints development server

### ISSUE THREAD

**Issue by shirey** [x-atlas-consortia/hs-ontology-api#116]
Create a standalone RESTful service that exposes two endpoints, 
  - `/assayclasses?application_context=HUBMAP`
  - `/assayclasses/<assay-code>?application_context=HUBMAP`

A framework for this service has been started in the [hs-ontology-api repo in the shirey/assayclass-dev-server branch under the /dev directory](https://github.com/x-atlas-consortia/hs-ontology-api/tree/shirey/assayclass-dev-server/dev)

Both endpoints require the `application_context=HUBMAP` parameter to be included, otherwise return a 400.

This service is intended to be for development purposes only, so a developer can easily control the output by changing the [assayclasses.json file in GitHub].  It is intended to mimic the services:

  - https://ontology-api.dev.hubmapconsortium.org/assayclasses?application_context=HUBMAP
  - https://ontology-api.dev.hubmapconsortium.org/assayclasses/C200150?application_context=HUBMAP

The `/assayclasses` endpoint simply returns the contents of the file https://raw.githubusercontent.com/x-atlas-consortia/hs-ontology-api/dev-integrate/dev/assayclasses.json as a json response.

The `/assayclasses/<assay-code>` endpoint searches the same [assayclasses.json file](https://raw.githubusercontent.com/x-atlas-consortia/hs-ontology-api/dev-integrate/dev/assayclasses.json) for an assayclass item matching `rule_description.code` and returns the full matching assayclass item as a json response.  If the code is not found a 404 is returned.  For example if `/assayclasses/C200001?application_context=HUBMAP` is called the return value is:

```
{
  "rule_description": {
    "application_context": "HUBMAP",
    "code": "C200150",
    "name": "non-DCWG primary IMC2D"
  },
  "value": {
    "active_status": "active",
    "assaytype": "IMC2D",
    "dataset_type": {
      "PDR_category": "MxNF",
      "dataset_type": "2D Imaging Mass Cytometry",
      "fig2": {
        "aggregated_assaytype": "LC-MS",
        "category": "bulk",
        "modality": "Proteomics"
      }
    },
    "description": "2D Imaging Mass Cytometry",
    "dir_schema": "imc-v0",
    "is_multiassay": false,
    "measurement_assay": {
      "codes": [
        {
          "code": "SENNET:C006901",
          "term": "Imaging Mass Cytometry Measurement Assay"
        },
        {
          "code": "HUBMAP:C006901",
          "term": "Imaging Mass Cytometry Measurement Assay"
        },
        {
          "code": "OBI:0003096",
          "term": "imaging mass cytometry assay"
        }
      ],
      "contains_full_genetic_sequences": false
    },
    "must_contain": [],
    "pipeline_shorthand": null,
    "process_state": "primary",
    "provider": "IEC",
    "tbl_schema": "imc-v",
    "vitessce_hints": []
  }
}
```

**Comment by ChuckKollar** [comment]
Bill, I have updated the app.py that you started and tested it with the test_api.sh script which I created. Please let me know if you have any suggestions or comments. Charles

**Comment by ChuckKollar** [comment]
PR: https://github.com/x-atlas-consortia/hs-ontology-api/pull/119

**Comment by yuanzhou** [comment]
I've also dockerized the dev server and handed over to PSC for their use.
