### ISSUE TITLE
Modify endpoints of ubkg-api/hs-ontology-api to account for CodeID format change from SAB<space>CODE to SAB:CODE

### ISSUE THREAD

**Issue by AlanSimmons** [x-atlas-consortia/hs-ontology-api#21]
The new version of the UBKG neo4j  (v3 architecture) is currently not compatible with endpoints of of the UBKG API. 

We recently deployed a HuBMAP/Sennet instance of UBKG to the DEV environment. @yuanzhou noticed that the following endpoints return empty arrays:

- https://ontology-api.dev.hubmapconsortium.org/assaytype?application_context=HUBMAP
- https://ontology-api.dev.hubmapconsortium.org/organs/by-code?application_context=HUBMAP

We have backed out the deployment to DEV.

I will review the code behind the endpoints. The solution could be as simple as revising the Cypher code that the endpoints use.

**Comment by ChuckKollar** [comment]
Alan, It appears that there is a typo in your description. There is no 'c.Parent', so I changed it to 'cParent'. Also, apparently the function parameter 'sab' is no longer used in __subquery_data_type_info?!

I ran the test_api.sh from ubkg-api and it appeared to return good data. On running test_api.sh from hs-antology-api  it seemed to return almost no data, but it did not break (e.g., 5xx error code).

**Comment by AlanSimmons** [comment]
1. The function parameter sab is used in _subquery_data_type_info in the line:

```'WHERE cParent.CodeID=\'' + sab + ' C004001\' '```

The sab parameter corresponds to the application context in the calling function.

2. The function itself is a subquery, and will return one data type per dataset type--e.g., the value "AF" for key "data_type" in the response of the datasets endpoint:

```{
"alt-names": [],
"contains-pii": false,
"data_type": "AF",
"dataset_provider": "HuBMAP IEC",
"description": "Autofluorescence Microscopy",
"primary": true,
"vis-only": false,
"vitessce-hints": []
},```
