### ISSUE TITLE
Remove the `/status` endpoint and rely on ubkg-api status endpoint

### ISSUE THREAD

**Issue by shirey** [x-atlas-consortia/hs-ontology-api#81]
Remove the `/status` endpoint and rely on the new status endpoint created by [ubkg-api add status endpoint #94](https://github.com/x-atlas-consortia/ubkg-api/issues/94) which will be inherited

**Comment by ChuckKollar** [comment]
The "/status" endpoint is in the "neo4jv5" branch of "ubkg-api" in "common_routes/status/status_controller.py". So, I will remove the "/status" endpoint from the "neo4jv5" branch of "hs-ontology-api".

**Comment by ChuckKollar** [comment]
There is a problem. It seems that the endpoint `/status` uses the Python variable __file__ to determine where to find the 'VERSION' and 'BUILD' files. However, the path to these files is different in both `hs-ontoloty-api' and 'ubkg-api'. So, I'm going to try to change `UbkgAPI` to take a second variable which is the location of these file.
