### ISSUE TITLE
Include endpoints from ubkg-api to hs-ontology-api

### ISSUE THREAD

**Issue by yuanzhou** [x-atlas-consortia/hs-ontology-api#94]
Currently the [endpoints exposed via the ubkg-api](https://smart-api.info/ui/96e5b5c0b0efeef5b93ea98ac2794837/) (PyPI package) are not included in the[ hs-ontology-api spec yaml](https://smart-api.info/ui/d10ff85265d8b749fbe3ad7b51d0bf0a) and thus not available in SmartAPI.

Add those endpoints to the AWS API Gateway.

**Comment by yuanzhou** [comment]
@AlanSimmons how do you want to maintain the yaml spec of ubkg-api within hs-ontology-api? Or we just merge them at the API Gateway level but keep two separate spec yamls?

**Comment by AlanSimmons** [comment]
Two separate spec yamls.
